version: "3"
services:
  telefoncaptainweb:
    image: telefoncaptain
    build: ./src
    container_name: telefoncaptainweb
    restart: unless-stopped
    ports:
     - ${PORT:-8080}:${PORT:-8080}
    environment:
     - PORT=${PORT}
     - HOSTNAME=${HOSTNAME}
